default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: deploy
  password: josefzacek
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: vagrant_development

